version: '3'

services:
  rendertron:
    restart: always
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.rendertron_secured.loadbalancer.server.port=3000"
      - "traefik.http.routers.rendertron_secured.rule=Host(`s.j42.org`) && PathPrefix(`/rendertron`)"
      - "traefik.http.routers.rendertron_secured.middlewares=rendertron-stripprefix"
      - "traefik.http.middlewares.rendertron-stripprefix.stripprefix.prefixes=/rendertron"
      - "traefik.http.routers.rendertron_secured.entrypoints=websecure"
      - "traefik.http.routers.rendertron_secured.tls=true"
      - "traefik.http.routers.rendertron_secured.tls.certresolver=myresolver"
    cap_add:
      - SYS_ADMIN
    networks:
      - web
      - default
networks:
  web:
    external: true
